@echo off
REM RegulatoryKB Intelligence Agent - IMAP Poll
REM Polls for digest reply emails every 30 minutes
REM Generated by RegulatoryKB

cd /d "%~dp0"

REM Activate virtual environment if exists
if exist ".venv\Scripts\activate.bat" (
    call .venv\Scripts\activate.bat
)

REM Set environment variables (edit these!)
REM IMAP uses same credentials as SMTP for Gmail
REM set IMAP_USERNAME=your-email@gmail.com
REM set IMAP_PASSWORD=your-app-password
REM (Or use SMTP_USERNAME / SMTP_PASSWORD)

REM Create logs directory
if not exist "logs" mkdir logs

:loop
echo.
echo ========================================
echo IMAP Poll - %date% %time%
echo ========================================

REM Poll for replies
python -m regkb intel poll --once

REM Log completion
echo %date% %time% - IMAP poll completed >> logs\intel_imap.log

REM Wait for next poll interval (30 minutes = 1800 seconds)
echo.
echo Waiting 30 minutes until next poll...
echo Press Ctrl+C to stop.
timeout /t 1800 /nobreak > nul

goto loop
