"""
Email delivery for regulatory intelligence.

Sends weekly digests, daily alerts, and monthly compilations via SMTP.
"""

import logging
import os
import smtplib
import ssl
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional, Tuple, TYPE_CHECKING

from ..config import config
from .filter import FilteredEntry
from .summarizer import Summary

if TYPE_CHECKING:
    from .digest_tracker import DigestEntry
    from .reply_handler import ProcessedDownload

logger = logging.getLogger(__name__)


@dataclass
class EmailConfig:
    """Email configuration."""

    smtp_server: str
    smtp_port: int
    sender: str
    recipients: List[str]
    username: Optional[str] = None
    password: Optional[str] = None
    use_tls: bool = True


@dataclass
class EmailResult:
    """Result of sending an email."""

    success: bool
    recipients_sent: int = 0
    error: Optional[str] = None


# HTML Email Templates
WEEKLY_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Regulatory Intelligence Weekly</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .container {{ background: white; border-radius: 8px; padding: 30px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .header {{ text-align: center; border-bottom: 3px solid #3182ce; padding-bottom: 20px; margin-bottom: 30px; }}
        .header h1 {{ color: #1a365d; margin: 0; font-size: 24px; }}
        .header .subtitle {{ color: #718096; font-size: 14px; margin-top: 5px; }}
        .summary-box {{ background: #ebf8ff; padding: 15px 20px; border-radius: 8px; margin: 20px 0; }}
        .summary-box h2 {{ color: #2c5282; font-size: 16px; margin: 0 0 10px 0; }}
        .summary-box ul {{ margin: 0; padding-left: 20px; }}
        .summary-box li {{ margin: 5px 0; }}
        .alert {{ background: #fed7d7; padding: 15px; border-left: 4px solid #c53030; margin: 15px 0; border-radius: 0 8px 8px 0; }}
        .alert.high {{ background: #fefcbf; border-color: #d69e2e; }}
        .alert h3 {{ color: #742a2a; margin: 0 0 5px 0; font-size: 14px; }}
        .alert.high h3 {{ color: #744210; }}
        .alert p {{ margin: 5px 0; font-size: 13px; color: #555; }}
        .section {{ margin: 30px 0; }}
        .section h2 {{ color: #2c5282; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }}
        .entry {{ padding: 15px; border: 1px solid #e2e8f0; border-radius: 8px; margin: 10px 0; }}
        .entry h3 {{ color: #2d3748; margin: 0 0 8px 0; font-size: 14px; }}
        .entry .meta {{ color: #718096; font-size: 12px; margin-bottom: 10px; }}
        .entry .summary {{ font-size: 13px; }}
        .entry .summary strong {{ color: #2c5282; }}
        .entry a {{ color: #3182ce; text-decoration: none; }}
        .entry a:hover {{ text-decoration: underline; }}
        .footer {{ text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }}
        .btn {{ display: inline-block; background: #3182ce; color: white; padding: 8px 16px; border-radius: 4px; text-decoration: none; font-size: 13px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Regulatory Intelligence Weekly</h1>
            <div class="subtitle">{date_range}</div>
        </div>

        <div class="summary-box">
            <h2>This Week at a Glance</h2>
            <ul>
                <li><strong>{total_updates}</strong> relevant regulatory updates</li>
                <li><strong>{high_priority}</strong> high-priority alerts</li>
                <li><strong>{categories}</strong> categories covered</li>
            </ul>
        </div>

        {alerts_section}

        {summaries_section}

        {reply_instructions}

        <div class="footer">
            <p>Generated by RegulatoryKB Intelligence Agent<br>
            Vertigenius Regulatory Consulting</p>
            <p style="font-size: 11px; color: #a0aec0;">
                You're receiving this because you're subscribed to regulatory intelligence updates.<br>
                Data source: Index-of-Indexes
            </p>
        </div>
    </div>
</body>
</html>"""

DAILY_ALERT_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Regulatory Alert</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
        .container {{ background: white; border-radius: 8px; padding: 25px; border: 2px solid #c53030; }}
        .header {{ text-align: center; margin-bottom: 20px; }}
        .header h1 {{ color: #c53030; margin: 0; font-size: 20px; }}
        .alert {{ background: #fff5f5; padding: 15px; border-radius: 8px; margin: 15px 0; }}
        .alert h2 {{ color: #742a2a; margin: 0 0 10px 0; font-size: 16px; }}
        .alert .meta {{ color: #718096; font-size: 12px; margin-bottom: 10px; }}
        .alert .content {{ font-size: 14px; }}
        .alert a {{ color: #c53030; }}
        .footer {{ text-align: center; margin-top: 20px; color: #718096; font-size: 11px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚨 Regulatory Alert</h1>
            <p style="color: #718096; font-size: 13px;">{date}</p>
        </div>

        {alerts_content}

        <div class="footer">
            <p>RegulatoryKB Intelligence Agent | Vertigenius</p>
        </div>
    </div>
</body>
</html>"""

REPLY_INSTRUCTIONS_TEMPLATE = """
<div style="background: #edf2f7; padding: 20px; border-radius: 8px; margin: 30px 0; border-left: 4px solid #3182ce;">
    <h3 style="color: #2c5282; margin: 0 0 10px 0; font-size: 14px;">
        Want to download documents to your knowledge base?
    </h3>
    <p style="margin: 0; font-size: 13px; color: #4a5568;">
        Reply to this email with entry IDs: <strong>"Download: 07, 12"</strong> or just <strong>"07, 12"</strong>
    </p>
</div>
"""

DOWNLOAD_CONFIRMATION_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Download Complete</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
        .container {{ background: white; border-radius: 8px; padding: 25px; border: 1px solid #e2e8f0; }}
        .header {{ text-align: center; margin-bottom: 20px; }}
        .header h1 {{ color: #2c5282; margin: 0; font-size: 20px; }}
        .summary {{ background: #ebf8ff; padding: 15px; border-radius: 8px; margin: 15px 0; }}
        .success {{ background: #f0fff4; padding: 12px; border-left: 4px solid #38a169; margin: 10px 0; border-radius: 0 8px 8px 0; }}
        .success h3 {{ color: #276749; margin: 0 0 5px 0; font-size: 14px; }}
        .manual {{ background: #fefcbf; padding: 12px; border-left: 4px solid #d69e2e; margin: 10px 0; border-radius: 0 8px 8px 0; }}
        .manual h3 {{ color: #744210; margin: 0 0 5px 0; font-size: 14px; }}
        .failed {{ background: #fed7d7; padding: 12px; border-left: 4px solid #c53030; margin: 10px 0; border-radius: 0 8px 8px 0; }}
        .failed h3 {{ color: #742a2a; margin: 0 0 5px 0; font-size: 14px; }}
        .entry {{ margin: 8px 0; font-size: 13px; }}
        .entry-id {{ font-family: monospace; background: #e2e8f0; padding: 2px 6px; border-radius: 4px; }}
        .kb-id {{ color: #38a169; font-weight: bold; }}
        .footer {{ text-align: center; margin-top: 20px; color: #718096; font-size: 11px; }}
        a {{ color: #3182ce; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Download Complete</h1>
            <p style="color: #718096; font-size: 13px;">{summary_line}</p>
        </div>

        {successful_section}

        {manual_section}

        {failed_section}

        <div class="footer">
            <p>RegulatoryKB Intelligence Agent | Vertigenius</p>
        </div>
    </div>
</body>
</html>"""

MONTHLY_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Regulatory Intelligence Monthly</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .container {{ background: white; border-radius: 8px; padding: 30px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .header {{ text-align: center; border-bottom: 3px solid #805ad5; padding-bottom: 20px; margin-bottom: 30px; }}
        .header h1 {{ color: #44337a; margin: 0; font-size: 24px; }}
        .executive {{ background: #faf5ff; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #805ad5; }}
        .executive h2 {{ color: #44337a; margin: 0 0 10px 0; font-size: 16px; }}
        .highlights {{ margin: 30px 0; }}
        .highlights h2 {{ color: #44337a; font-size: 18px; }}
        .highlight-item {{ padding: 15px; border: 1px solid #e9d8fd; border-radius: 8px; margin: 10px 0; background: #faf5ff; }}
        .highlight-item h3 {{ color: #553c9a; margin: 0 0 8px 0; font-size: 14px; }}
        .action-items {{ background: #f0fff4; padding: 20px; border-radius: 8px; margin: 20px 0; }}
        .action-items h2 {{ color: #276749; margin: 0 0 15px 0; font-size: 16px; }}
        .action-items ul {{ margin: 0; padding-left: 20px; }}
        .footer {{ text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Regulatory Intelligence Monthly</h1>
            <div style="color: #718096; font-size: 14px;">{month_year}</div>
        </div>

        <div class="executive">
            <h2>Executive Summary</h2>
            <p>{executive_summary}</p>
        </div>

        {highlights_section}

        {action_items_section}

        <div class="footer">
            <p>Generated by RegulatoryKB Intelligence Agent<br>
            Vertigenius Regulatory Consulting</p>
        </div>
    </div>
</body>
</html>"""


class Emailer:
    """Sends regulatory intelligence emails via SMTP."""

    def __init__(self) -> None:
        """Initialize the emailer with configuration."""
        self.config = self._load_config()

    def _load_config(self) -> EmailConfig:
        """Load email configuration from config file and environment."""
        return EmailConfig(
            smtp_server=config.get("intelligence.email.smtp_server", "smtp.gmail.com"),
            smtp_port=config.get("intelligence.email.smtp_port", 587),
            sender=config.get("intelligence.email.sender", "regulatory@vertigenius.com"),
            recipients=config.get("intelligence.email.recipients", []),
            username=os.environ.get("SMTP_USERNAME"),
            password=os.environ.get("SMTP_PASSWORD"),
            use_tls=True,
        )

    def _create_message(
        self,
        subject: str,
        html_content: str,
        plain_content: str,
        recipients: Optional[List[str]] = None,
    ) -> MIMEMultipart:
        """Create a MIME multipart email message."""
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.config.sender
        msg["To"] = ", ".join(recipients or self.config.recipients)

        # Plain text version
        msg.attach(MIMEText(plain_content, "plain"))

        # HTML version
        msg.attach(MIMEText(html_content, "html"))

        return msg

    def _send_email(self, msg: MIMEMultipart, recipients: List[str]) -> EmailResult:
        """Send an email via SMTP."""
        if not recipients:
            return EmailResult(success=False, error="No recipients specified")

        if not self.config.username or not self.config.password:
            return EmailResult(
                success=False,
                error="SMTP credentials not set. Set SMTP_USERNAME and SMTP_PASSWORD environment variables.",
            )

        try:
            context = ssl.create_default_context()

            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls(context=context)

                server.login(self.config.username, self.config.password)
                server.sendmail(self.config.sender, recipients, msg.as_string())

            logger.info(f"Email sent successfully to {len(recipients)} recipients")
            return EmailResult(success=True, recipients_sent=len(recipients))

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            return EmailResult(success=False, error="SMTP authentication failed. Check credentials.")

        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {e}")
            return EmailResult(success=False, error=f"SMTP error: {str(e)}")

        except Exception as e:
            logger.error(f"Email send failed: {e}")
            return EmailResult(success=False, error=str(e))

    def _generate_alerts_section(
        self,
        high_priority: List[Tuple[FilteredEntry, Optional[Summary]]],
        entry_ids: Optional[Dict[int, str]] = None,
        all_entries: Optional[List[Tuple[FilteredEntry, Optional[Summary]]]] = None,
    ) -> str:
        """Generate HTML for the alerts section."""
        if not high_priority:
            return ""

        # Build mapping from entry to its ID in the full list
        id_map = entry_ids or {}
        entry_to_idx = {}
        if all_entries:
            for idx, (entry, _) in enumerate(all_entries):
                entry_to_idx[id(entry)] = idx

        html = '<div class="section"><h2>High Priority Alerts</h2>'

        for entry, summary in high_priority[:10]:
            alert_class = "alert" if entry.alert_level == "critical" else "alert high"

            # Get entry ID if available
            idx = entry_to_idx.get(id(entry))
            entry_id = id_map.get(idx) if idx is not None else None
            id_badge = ""
            if entry_id:
                seq = entry_id.split("-")[-1] if "-" in entry_id else entry_id
                id_badge = f'<span style="background: white; color: #742a2a; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 11px; margin-right: 6px;">[{seq}]</span>'

            html += f'''
            <div class="{alert_class}">
                <h3>{id_badge}{entry.entry.title}</h3>
                <p class="meta">{entry.entry.agency} | {entry.entry.date}</p>
                {f"<p>{summary.what_happened}</p>" if summary and summary.what_happened else ""}
                {f'<p><a href="{entry.entry.link}">View source →</a></p>' if entry.entry.link else ""}
            </div>
            '''

        html += "</div>"
        return html

    def _generate_summaries_section(
        self,
        entries_with_summaries: List[Tuple[FilteredEntry, Optional[Summary]]],
        by_category: bool = True,
        entry_ids: Optional[Dict[int, str]] = None,
    ) -> str:
        """Generate HTML for the summaries section."""
        if not entries_with_summaries:
            return ""

        # Build a mapping from entry index to ID if provided
        id_map = entry_ids or {}

        if by_category:
            # Group by category, preserving original index
            categories: Dict[str, List] = {}
            for idx, (entry, summary) in enumerate(entries_with_summaries):
                cat = entry.entry.category or "Other"
                if cat not in categories:
                    categories[cat] = []
                categories[cat].append((idx, entry, summary))

            html = ""
            for category, items in sorted(categories.items(), key=lambda x: -len(x[1])):
                html += f'<div class="section"><h2>{category} ({len(items)})</h2>'
                for idx, entry, summary in items[:5]:  # Limit per category
                    entry_id = id_map.get(idx)
                    html += self._format_entry(entry, summary, entry_id)
                html += "</div>"

            return html
        else:
            html = '<div class="section"><h2>Updates</h2>'
            for idx, (entry, summary) in enumerate(entries_with_summaries[:15]):
                entry_id = id_map.get(idx)
                html += self._format_entry(entry, summary, entry_id)
            html += "</div>"
            return html

    def _format_entry(
        self,
        entry: FilteredEntry,
        summary: Optional[Summary],
        entry_id: Optional[str] = None,
    ) -> str:
        """Format a single entry for email."""
        # Include entry ID badge if provided
        id_badge = ""
        if entry_id:
            # Extract just the sequence number for display
            seq = entry_id.split("-")[-1] if "-" in entry_id else entry_id
            id_badge = f'<span style="display: inline-block; background: #3182ce; color: white; padding: 2px 8px; border-radius: 4px; font-family: monospace; font-size: 12px; margin-right: 8px;">[{seq}]</span>'

        html = f'''
        <div class="entry">
            <h3>{id_badge}{entry.entry.title}</h3>
            <div class="meta">{entry.entry.agency} | {entry.entry.date} | {entry.entry.category or "Update"}</div>
        '''

        if summary:
            if summary.what_happened:
                html += f'<div class="summary"><strong>What:</strong> {summary.what_happened}</div>'
            if summary.why_it_matters:
                html += f'<div class="summary"><strong>Why:</strong> {summary.why_it_matters}</div>'
            if summary.action_needed and summary.action_needed.lower() not in ("information only", "no action"):
                html += f'<div class="summary"><strong>Action:</strong> {summary.action_needed}</div>'

        if entry.entry.link:
            html += f'<p><a href="{entry.entry.link}">Read more →</a></p>'

        html += "</div>"
        return html

    def _html_to_plain(self, html: str) -> str:
        """Convert HTML to plain text (basic conversion)."""
        import re

        # Remove style tags
        text = re.sub(r"<style[^>]*>.*?</style>", "", html, flags=re.DOTALL)
        # Replace breaks with newlines
        text = re.sub(r"<br\s*/?>", "\n", text)
        # Replace headers with text and underline
        text = re.sub(r"<h[12][^>]*>([^<]+)</h[12]>", r"\n\1\n" + "=" * 40 + "\n", text)
        text = re.sub(r"<h[3-6][^>]*>([^<]+)</h[3-6]>", r"\n\1\n", text)
        # Replace links
        text = re.sub(r'<a[^>]*href="([^"]*)"[^>]*>([^<]*)</a>', r"\2 [\1]", text)
        # Remove remaining tags
        text = re.sub(r"<[^>]+>", "", text)
        # Clean up whitespace
        text = re.sub(r"\n\s*\n", "\n\n", text)
        text = re.sub(r"  +", " ", text)

        return text.strip()

    def send_weekly_digest(
        self,
        entries_with_summaries: List[Tuple[FilteredEntry, Optional[Summary]]],
        high_priority: List[Tuple[FilteredEntry, Optional[Summary]]],
        date_range: str,
        recipients: Optional[List[str]] = None,
        track_entries: bool = True,
    ) -> EmailResult:
        """
        Send the weekly digest email.

        Args:
            entries_with_summaries: List of (FilteredEntry, Summary) tuples.
            high_priority: High priority entries.
            date_range: Human-readable date range string.
            recipients: Optional override for recipients.
            track_entries: Whether to track entries for reply processing.

        Returns:
            EmailResult with send status.
        """
        from .digest_tracker import digest_tracker

        # Generate entry IDs and track
        entry_ids: Dict[int, str] = {}
        digest_date = datetime.now()
        tracked_entries = []

        if track_entries:
            # Track entries and get their IDs
            just_entries = [entry for entry, _ in entries_with_summaries]
            tracked = digest_tracker.record_digest(just_entries, digest_date)

            # Build mapping from index to entry ID
            for idx, tracked_entry in enumerate(tracked):
                entry_ids[idx] = tracked_entry.entry_id

        # Count categories
        categories = set(e.entry.category for e, _ in entries_with_summaries if e.entry.category)

        # Generate sections with entry IDs
        alerts_section = self._generate_alerts_section(
            high_priority,
            entry_ids=entry_ids,
            all_entries=entries_with_summaries,
        )
        summaries_section = self._generate_summaries_section(
            entries_with_summaries,
            entry_ids=entry_ids,
        )

        # Reply instructions
        reply_instructions = REPLY_INSTRUCTIONS_TEMPLATE if track_entries else ""

        # Build HTML
        html = WEEKLY_TEMPLATE.format(
            date_range=date_range,
            total_updates=len(entries_with_summaries),
            high_priority=len(high_priority),
            categories=len(categories),
            alerts_section=alerts_section,
            summaries_section=summaries_section,
            reply_instructions=reply_instructions,
        )

        plain = self._html_to_plain(html)

        # Create subject
        subject_template = config.get(
            "intelligence.email.weekly_subject",
            "Regulatory Intelligence Weekly - {date_range}",
        )
        subject = subject_template.format(date_range=date_range)

        # Create and send message with Message-ID for threading
        recipients = recipients or self.config.recipients
        msg = self._create_message(subject, html, plain, recipients)

        # Add Message-ID for threading replies
        message_id = f"<regkb-digest-{digest_date.strftime('%Y%m%d-%H%M%S')}@{self.config.sender.split('@')[-1]}>"
        msg["Message-ID"] = message_id

        result = self._send_email(msg, recipients)

        # Update digest with message ID if tracking
        if track_entries and result.success:
            logger.info(f"Tracked {len(entry_ids)} entries for digest with Message-ID: {message_id}")

        return result

    def send_daily_alert(
        self,
        alerts: List[Tuple[FilteredEntry, Optional[Summary]]],
        recipients: Optional[List[str]] = None,
    ) -> EmailResult:
        """
        Send a daily alert email for high-priority items.

        Args:
            alerts: List of high-priority (FilteredEntry, Summary) tuples.
            recipients: Optional override for recipients.

        Returns:
            EmailResult with send status.
        """
        if not alerts:
            return EmailResult(success=False, error="No alerts to send")

        # Generate alerts content
        alerts_content = ""
        for entry, summary in alerts:
            alerts_content += f'''
            <div class="alert">
                <h2>{entry.entry.title}</h2>
                <div class="meta">{entry.entry.agency} | {entry.entry.category}</div>
                <div class="content">
                    {f"<p><strong>What:</strong> {summary.what_happened}</p>" if summary and summary.what_happened else ""}
                    {f"<p><strong>Why:</strong> {summary.why_it_matters}</p>" if summary and summary.why_it_matters else ""}
                    {f'<p><a href="{entry.entry.link}">View source →</a></p>' if entry.entry.link else ""}
                </div>
            </div>
            '''

        html = DAILY_ALERT_TEMPLATE.format(
            date=datetime.now().strftime("%B %d, %Y"),
            alerts_content=alerts_content,
        )

        plain = self._html_to_plain(html)
        subject = f"🚨 Regulatory Alert - {len(alerts)} High Priority Update{'s' if len(alerts) > 1 else ''}"

        recipients = recipients or self.config.recipients
        msg = self._create_message(subject, html, plain, recipients)

        return self._send_email(msg, recipients)

    def send_monthly_digest(
        self,
        highlights: List[Tuple[FilteredEntry, Optional[Summary]]],
        executive_summary: str,
        action_items: List[str],
        month_year: str,
        recipients: Optional[List[str]] = None,
    ) -> EmailResult:
        """
        Send the monthly compilation email.

        Args:
            highlights: Top highlights with summaries.
            executive_summary: 3-5 sentence executive summary.
            action_items: List of action items.
            month_year: Month and year string (e.g., "January 2026").
            recipients: Optional override for recipients.

        Returns:
            EmailResult with send status.
        """
        # Generate highlights section
        highlights_html = '<div class="highlights"><h2>Top Highlights</h2>'
        for entry, summary in highlights[:15]:
            highlights_html += f'''
            <div class="highlight-item">
                <h3>{entry.entry.title}</h3>
                <p style="color: #718096; font-size: 12px;">{entry.entry.agency} | {entry.entry.date}</p>
                {f"<p>{summary.what_happened}</p>" if summary and summary.what_happened else ""}
            </div>
            '''
        highlights_html += "</div>"

        # Generate action items section
        if action_items:
            action_html = '<div class="action-items"><h2>Key Action Items</h2><ul>'
            for item in action_items:
                action_html += f"<li>{item}</li>"
            action_html += "</ul></div>"
        else:
            action_html = ""

        html = MONTHLY_TEMPLATE.format(
            month_year=month_year,
            executive_summary=executive_summary,
            highlights_section=highlights_html,
            action_items_section=action_html,
        )

        plain = self._html_to_plain(html)

        subject_template = config.get(
            "intelligence.email.monthly_subject",
            "Regulatory Intelligence Monthly - {month} {year}",
        )
        parts = month_year.split()
        subject = subject_template.format(month=parts[0], year=parts[1] if len(parts) > 1 else "")

        recipients = recipients or self.config.recipients
        msg = self._create_message(subject, html, plain, recipients)

        return self._send_email(msg, recipients)

    def send_test_email(self, recipient: str) -> EmailResult:
        """Send a test email to verify configuration."""
        html = """
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h1 style="color: #3182ce;">RegulatoryKB Test Email</h1>
            <p>This is a test email from the Regulatory Intelligence Agent.</p>
            <p>If you received this, your email configuration is working correctly.</p>
            <hr>
            <p style="color: #718096; font-size: 12px;">Sent from RegulatoryKB</p>
        </body>
        </html>
        """
        plain = "RegulatoryKB Test Email\n\nThis is a test email. Your configuration is working."

        msg = self._create_message("RegulatoryKB - Test Email", html, plain, [recipient])
        return self._send_email(msg, [recipient])

    def send_download_confirmation(
        self,
        successful: List["ProcessedDownload"],
        needs_manual: List["ProcessedDownload"],
        failed: List["ProcessedDownload"],
        requester_email: str,
    ) -> EmailResult:
        """
        Send a confirmation email after processing download requests.

        Args:
            successful: List of successfully downloaded entries.
            needs_manual: List of entries needing manual URL.
            failed: List of failed downloads.
            requester_email: Email address to send confirmation to.

        Returns:
            EmailResult with send status.
        """
        total = len(successful) + len(needs_manual) + len(failed)
        summary_line = f"{len(successful)} of {total} documents processed"

        # Generate successful section
        successful_section = ""
        if successful:
            successful_section = '<h2 style="color: #276749;">Successful Downloads</h2>'
            for download in successful:
                kb_id = f' <span class="kb-id">(KB ID: {download.kb_doc_id})</span>' if download.kb_doc_id else ""
                seq = download.entry.entry_id.split("-")[-1] if "-" in download.entry.entry_id else download.entry.entry_id

                # Content warning badge
                content_badge = ""
                cw = getattr(download, "content_warning", None)
                if cw:
                    content_badge = f'''
                    <div style="background: #fefcbf; padding: 8px 12px; margin-top: 6px;
                                border-radius: 4px; font-size: 12px; color: #744210;">
                        <strong>Warning:</strong> {cw}
                    </div>
                    '''

                # Version diff badge
                version_badge = ""
                vd = getattr(download, "version_diff", None)
                if vd and vd.stats:
                    sim_pct = f"{vd.stats.similarity:.0%}"
                    auto_super = getattr(vd, "auto_superseded", True)
                    if auto_super:
                        version_badge = f'''
                        <div style="background: #ebf8ff; padding: 8px 12px; margin-top: 6px;
                                    border-radius: 4px; font-size: 12px; color: #2c5282;">
                            <strong>Version update detected:</strong>
                            Supersedes [{vd.old_doc_id}] {vd.old_doc_title[:60]}<br>
                            Similarity: {sim_pct} |
                            Added: {vd.stats.added} |
                            Removed: {vd.stats.removed} |
                            Changed: {vd.stats.changed}
                        </div>
                        '''
                    else:
                        version_badge = f'''
                        <div style="background: #fefcbf; padding: 8px 12px; margin-top: 6px;
                                    border-radius: 4px; font-size: 12px; color: #744210;">
                            <strong>Possible version match — NOT auto-superseded:</strong>
                            Candidate [{vd.old_doc_id}] {vd.old_doc_title[:60]}<br>
                            Similarity: {sim_pct} (below threshold) |
                            Use <code>regkb diff {vd.old_doc_id} {vd.new_doc_id}</code> to review
                        </div>
                        '''

                successful_section += f'''
                <div class="success">
                    <div class="entry">
                        <span class="entry-id">[{seq}]</span>
                        {download.entry.title}{kb_id}
                    </div>
                    {content_badge}
                    {version_badge}
                </div>
                '''

        # Generate manual section
        manual_section = ""
        if needs_manual:
            manual_section = '<h2 style="color: #744210;">Needs Manual URL</h2>'
            manual_section += '<p style="font-size: 12px; color: #744210;">Reply with the direct document URL to retry these downloads.</p>'
            for download in needs_manual:
                seq = download.entry.entry_id.split("-")[-1] if "-" in download.entry.entry_id else download.entry.entry_id
                manual_section += f'''
                <div class="manual">
                    <div class="entry">
                        <span class="entry-id">[{seq}]</span>
                        {download.entry.title}
                    </div>
                    <p style="font-size: 12px; margin: 5px 0 0 0;">
                        Original URL: <a href="{download.entry.link}">{download.entry.link[:60]}...</a>
                    </p>
                </div>
                '''

        # Generate failed section
        failed_section = ""
        if failed:
            failed_section = '<h2 style="color: #742a2a;">Failed Downloads</h2>'
            for download in failed:
                seq = download.entry.entry_id.split("-")[-1] if "-" in download.entry.entry_id else download.entry.entry_id
                failed_section += f'''
                <div class="failed">
                    <div class="entry">
                        <span class="entry-id">[{seq}]</span>
                        {download.entry.title}
                    </div>
                    <p style="font-size: 12px; margin: 5px 0 0 0; color: #c53030;">
                        Error: {download.error or "Unknown error"}
                    </p>
                </div>
                '''

        # Build HTML
        html = DOWNLOAD_CONFIRMATION_TEMPLATE.format(
            summary_line=summary_line,
            successful_section=successful_section,
            manual_section=manual_section,
            failed_section=failed_section,
        )

        plain = self._html_to_plain(html)
        subject = f"Download Complete - {len(successful)} of {total} documents processed"

        # Extract email address from "Name <email>" format
        import re
        match = re.search(r"<([^>]+)>", requester_email)
        recipient = match.group(1) if match else requester_email

        msg = self._create_message(subject, html, plain, [recipient])

        return self._send_email(msg, [recipient])


# Global emailer instance
emailer = Emailer()
